config/routes.rb
Rails.application.routes.draw do

  root to: 'home#home'

  match '/admin', to: 'admin#index', via: 'get'
  match '/rental', to: 'rental#index', via: 'get'
  resources :admin
  resources :rental
  resources :memberships
  resources :dvds
  resources :cards
  resources :users
  resources :orders
  #map.resources :orders, :has_many => [ :order_items ]
  resources :orders do
    resources :order_items
  end



  # The priority is based upon orders of creation: first created -> highest priority.
  # See how all your routes lay out with "rake routes".

  # You can have the root of your site routed with "root"
  # root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  has_many :users, :foreign_key => 'memid'
  before_destroy :ensure_not_referenced_by_any_user

  def ensure_not_referenced_by_any_user
    if users.empty?
      return true
    else
      errors.add(:base, 'There are active associated user')
      return false
    end
  end
end

app/controllers/memberships_controller.rb
class MembershipsController < AdminController
  before_action :set_membership, only: [:show, :edit, :update, :destroy]

  # GET /memberships
  # GET /memberships.json
  def index
    @memberships = Membership.all
  end

  # GET /memberships/1
  # GET /memberships/1.json
  def show
  end

  # GET /memberships/new
  def new
    @membership = Membership.new
  end

  # GET /memberships/1/edit
  def edit
  end

  # POST /memberships
  # POST /memberships.json
  def create
    @membership = Membership.new(membership_params)

    respond_to do |format|
      if @membership.save
        format.html { redirect_to @membership, notice: 'Membership was successfully created.' }
        format.json { render :show, status: :created, location: @membership }
      else
        format.html { render :new }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /memberships/1
  # PATCH/PUT /memberships/1.json
  def update
    respond_to do |format|
      if @membership.update(membership_params)
        format.html { redirect_to @membership, notice: 'Membership was successfully updated.' }
        format.json { render :show, status: :ok, location: @membership }
      else
        format.html { render :edit }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memberships/1
  # DELETE /memberships/1.json
  def destroy
    @membership.destroy
    respond_to do |format|
      format.html { redirect_to memberships_url, notice: 'Membership was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_membership
      @membership = Membership.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def membership_params
      params.require(:membership).permit(:memid, :memname, :status, :validmonths, :cost, :freetrans, :costadd)
    end
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/views/memberships/_form.html.erb
<%= form_for(@membership) do |f| %>
    <% if @membership.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@membership.errors.count, "error") %> prohibited this membership from being saved:</h2>

          <ul>
            <% @membership.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :memid %><br>
      <%= f.text_field :memid %>
    </div>
    <div class="field">
      <%= f.label :memname %><br>
      <%= f.text_field :memname %>
    </div>
    <div class="field">
      <%= f.label :status %><br>
      <%= f.number_field :status %>
    </div>
    <div class="field">
      <%= f.label :validmonths %><br>
      <%= f.number_field :validmonths %>
    </div>
    <div class="field">
      <%= f.label :cost %><br>
      <%= f.number_field :cost %>
    </div>
    <div class="field">
      <%= f.label :freetrans %><br>
      <%= f.number_field :freetrans %>
    </div>
    <div class="field">
      <%= f.label :costadd %><br>
      <%= f.text_field :costadd %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/memberships/edit.html.erb
<!DOCTYPE html>
<html>
<div class="container">
  <div class="jumbotron">
    <p class="lead">

    <h1>Editing membership</h1>

    <%= render 'form' %>

    <%= link_to 'Show', @membership %> |
    <%= link_to 'Back', memberships_path %>
    </p>
  </div>
</div>
</html>

app/views/memberships/index.html.erb
<!DOCTYPE html>
<html>
<div class="container">
  <div class="jumbotron">
    <p class="lead">


    <h1>Listing memberships</h1>

    <table class="table">
      <thead>
      <tr>
        <th>Memid</th>
        <th>Memname</th>
        <th>Status</th>
        <th>Validmonths</th>
        <th>Cost</th>
        <th>Freetrans</th>
        <th>Cost add</th>
        <th colspan="3"></th>
      </tr>
      </thead>

      <tbody>
      <% @memberships.each do |membership| %>
          <tr>
            <td><%= membership.memid %></td>
            <td><%= membership.memname %></td>
            <td><%= membership.status %></td>
            <td><%= membership.validmonths %></td>
            <td><%= membership.cost %></td>
            <td><%= membership.freetrans %></td>
            <td><%= membership.costadd %></td>
            <td><%= link_to 'Show', membership %></td>
            <td><%= link_to 'Edit', edit_membership_path(membership) %></td>
            <td><%= link_to 'Destroy', membership, method: :delete, data: {confirm: 'Are you sure?'} %></td>
          </tr>
      <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New Membership', new_membership_path %>
    </p>
  </div>
</div>
</html>

app/views/memberships/new.html.erb
<!DOCTYPE html>
<html>
<div class="container">
  <div class="jumbotron">
    <p class="lead">

<h1>New membership</h1>

<%= render 'form' %>

<%= link_to 'Back', memberships_path %>
    </p>
  </div>
</div>
</html>

app/views/memberships/show.html.erb
<!DOCTYPE html>
<html>
<div class="container">
  <div class="jumbotron">
    <p class="lead">
    <p id="notice"><%= notice %></p>
<p>
  <strong>Memid:</strong>
  <%= @membership.memid %>
</p>

<p>
  <strong>Memname:</strong>
  <%= @membership.memname %>
</p>

<p>
  <strong>Status:</strong>
  <%= @membership.status %>
</p>

<p>
  <strong>Validmonths:</strong>
  <%= @membership.validmonths %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @membership.cost %>
</p>

<p>
  <strong>Freetrans:</strong>
  <%= @membership.freetrans %>
</p>

<p>
  <strong>Cost add:</strong>
  <%= @membership.costadd %>
</p>

<%= link_to 'Edit', edit_membership_path(@membership) %> |
<%= link_to 'Back', memberships_path %>

</p>
</div>
</div>
</html>