config/routes.rb
Rails.application.routes.draw do

  root to: 'home#home'

  match '/admin', to: 'admin#index', via: 'get'
  match '/rental', to: 'rental#index', via: 'get'
  resources :admin
  resources :rental
  resources :memberships
  resources :dvds
  resources :cards
  resources :users
  resources :orders
  #map.resources :orders, :has_many => [ :order_items ]
  resources :orders do
    resources :order_items
  end



  # The priority is based upon orders of creation: first created -> highest priority.
  # See how all your routes lay out with "rake routes".

  # You can have the root of your site routed with "root"
  # root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/admin/index.html.erb
<!DOCTYPE html>
<html>
<div class="container">
  <div class="row text-center">
  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
  <br>
    <br>
    <h1>Admin Module</h1>
    <br>
    <br>

    <div class="banner">
      <div class="btn-block">
    <div class="col-lg-3">        <%= link_to "Manage User", users_path, :class => "btn btn-lg btn-primary"    %>
    </div>
        <div class="col-lg-3">        <%= link_to "Manage Membership", memberships_path, :class => "btn btn-lg btn-primary"    %>
        </div>
<div class="col-lg-3">        <%= link_to "Manage Card", cards_path, :class => "btn btn-lg btn-primary"    %>
</div>
        <div class="col-lg-3">
          <%= link_to "Manage DVD", dvds_path, :class => "btn btn-lg btn-primary"    %>

        </div>

      </div>

    </div>
  </div>
  </div>
</div>
</html>