config/routes.rb
Rails.application.routes.draw do

  root to: 'home#home'

  match '/admin', to: 'admin#index', via: 'get'
  match '/rental', to: 'rental#index', via: 'get'
  resources :admin
  resources :rental
  resources :memberships
  resources :dvds
  resources :cards
  resources :users
  resources :orders
  #map.resources :orders, :has_many => [ :order_items ]
  resources :orders do
    resources :order_items
  end



  # The priority is based upon orders of creation: first created -> highest priority.
  # See how all your routes lay out with "rake routes".

  # You can have the root of your site routed with "root"
  # root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/card.rb
class Card < ActiveRecord::Base
  belongs_to :user,:foreign_key => 'userid'
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.all
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url, notice: 'Card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params.require(:card).permit(:cardid, :userid, :status, :card_num, :pw, :balance)
    end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_form.html.erb
<%= form_for(@card) do |f| %>
  <% if @card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
      <% @card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cardid %><br>
    <%= f.text_field :cardid %>
  </div>
  <div class="field">
    <%= f.label :userid %><br>
    <%= f.text_field :userid %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.number_field :status %>
  </div>
  <div class="field">
    <%= f.label :cardnum %><br>
    <%= f.text_field :cardnum %>
  </div>
  <div class="field">
    <%= f.label :pw %><br>
    <%= f.text_field :pw %>
  </div>
  <div class="field">
    <%= f.label :balance %><br>
    <%= f.text_field :balance %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<!DOCTYPE html>
<html>
<div class="container">
  <div class="jumbotron">
    <p class="lead">

    <h1>Editing card</h1>

<%= render 'form' %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>
    </p>
  </div>
</div>
</html>

app/views/cards/index.html.erb
<!DOCTYPE html>
<html>
<div class="container">
  <div class="jumbotron">
    <p class="lead">

    <h1>Listing cards</h1>

<table class="table">
  <thead>
    <tr>
      <th>Cardid</th>
      <th>Userid</th>
      <th>Status</th>
      <th>Card num</th>
      <th>Pw</th>
      <th>Balance</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cards.each do |card| %>
      <tr>
        <td><%= card.cardid %></td>
        <td><%= card.userid %></td>
        <td><%= card.status %></td>
        <td><%= card.cardnum %></td>
        <td><%= card.pw %></td>
        <td><%= card.balance %></td>
        <td><%= link_to 'Show', card %></td>
        <td><%= link_to 'Edit', edit_card_path(card) %></td>
        <td><%= link_to 'Destroy', card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Card', new_card_path %>
    </p>
  </div>
</div>
</html>

app/views/cards/new.html.erb
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/html">
<div class="container">
  <div class="jumbotron">
    <p class="lead">
<h1>New card</h1>

<%= render 'form' %>

<%= link_to 'Back', cards_path %>
</p>
    </div>
  </div>
</html>

app/views/cards/show.html.erb
<!DOCTYPE html>
<html>
<div class="container">
  <div class="jumbotron">
    <p class="lead">
<p id="notice"><%= notice %></p>

<p>
  <strong>Cardid:</strong>
  <%= @card.cardid %>
</p>

<p>
  <strong>Userid:</strong>
  <%= @card.userid %>
</p>

<p>
  <strong>Status:</strong>
  <%= @card.status %>
</p>

<p>
  <strong>Card num:</strong>
  <%= @card.cardnum %>
</p>

<p>
  <strong>Pw:</strong>
  <%= @card.pw %>
</p>

<p>
  <strong>Balance:</strong>
  <%= @card.balance %>
</p>

<%= link_to 'Edit', edit_card_path(@card) %> |
<%= link_to 'Back', cards_path %>
    </p>
  </div>
</div>
</html>